<?php
/**
 * Created by PhpStorm.
 * User: ibrahim
 * Date: 7/21/2017
 * Time: 11:24
 */

namespace kouosl\theme\widgets;


class Tabs extends \yii\bootstrap\Tabs
{
        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
        }
}